### ISSUE TITLE
Language settings for FB comments plugin

### ISSUE THREAD

**Issue by saiscode** [godofredoninja/Mapache#1]
You should add instructions in the README file to tell people how to change the default language in the FB comments plugin.

They will need to open line #35 of default.hbs and edit the **highlighted** field below to the language of their choice.

> js.src = "//connect.facebook.net/**es_US**/sdk.js#xfbml=1&version=v2.4";

Language options are at https://developers.facebook.com/docs/plugins/like-button#language and https://www.facebook.com/translations/FacebookLocales.xml

Edit - I'm using your theme at http://ramachandr.in/

**Comment by iamkhush** [comment]
+1

**Comment by godofredoninja** [comment]
completed with revision 53ee572774a31e9f572c9363b4841512a6841fa1
