### ISSUE TITLE
differences between Mapache VS Simply?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [godofredoninja/Mapache#102]
Are both ghost theme's exactly the same, you just have more star's one repo than the other?

good work, i never met anyone from Puru with high quality like you.

**Comment by godofredoninja** [comment]
Hi @grand-lotus-iroh 

**Simply** — It's inspired by [Medium ](https://medium.com/)
**Mapche** — It is a very nice theme and has several publication templates.
