### ISSUE TITLE
Lighthouse improvements

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#103]
Can you try to improve the performance of this theme based on [Lighthouse analysis](https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://godofredo.ninja/)?

**Comment by godofredoninja** [comment]
Hi @MaluNoPeleke 

Next week, I'm gonna do a better mapache theme.

If you have more suggestions, you are welcome.

**Comment by MaluNoPeleke** [comment]
Thanks a lot!
