### ISSUE TITLE
Deobfuscate source css

### ISSUE THREAD

**Issue by EthanZeigler** [godofredoninja/Mapache#104]
It's really hard to make edits to the theming without a unminified css file. Honestly, I don't think the git repo's css should be like this and while expanding it again is easy it just gets messy.

Plus, this screams 'I need scss.' It's so hard to read and frustrating given it's an editable theme.

**Comment by godofredoninja** [comment]
hi @EthanZeigler 

You do not need to edit the original file. I'm mostly reusing the styles. 

What you can do is create a new CSS file and add your modifications. 

When I do an optimization and reordering of the code, I will release the development version.
