### ISSUE TITLE
Menu and search not working in 3.0.8

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#105]
After the upgrade to 3.0.8 the menu doesn't open anymore and the search doesn't show any results.
It worked before with 3.0.6 and all of the code is still correctly set up in the admin backend.
How can I fix it?
https://www.peleke.de/

**Comment by godofredoninja** [comment]
Hello: @MaluNoPeleke 

:thinking:  The ghost api changed so I had to change too

- Read the documentation
https://github.com/godofredoninja/Mapache#6-search

Change `host` for `url`

```html
<script>
  var searchSettings = {
    key: 'ADD_YOUR_API_KEY',
    url: 'https://demo.ghost.io',
  };
</script>
```

If you are using a theme color. Also update so you can see well.

https://github.com/godofredoninja/Mapache#change-theme-color

**Comment by godofredoninja** [comment]
Please also update the social media.
https://github.com/godofredoninja/Mapache#1-social-media-links

**Comment by MaluNoPeleke** [comment]
Thanks, didn't pay enough attention to those subtle changes.
