### ISSUE TITLE
Missing Sidebar Form (required) Input Validation

### ISSUE THREAD

**Issue by grand-lotus-iroh** [godofredoninja/Mapache#106]
The sidebar Newsletter module does not have form validation.

I think, a person should not be able to click "Subscribe" unless there is an **@** symbol.

* https://www.the-art-of-web.com/html/html5-form-validation/
* https://www.w3schools.com/tags/att_input_required.asp

**Comment by godofredoninja** [comment]
In the new version you already have a validation
