### ISSUE TITLE
Single tag page banner image always centered when displayed in the Archive tag page

### ISSUE THREAD

**Issue by stephanefr** [godofredoninja/Mapache#108]
The Archive tag page use the banner image from the tag associated image.
The banner image is ~700px long, while the Archive tag image is ~400px and square.
Example banner :
![bparis](https://user-images.githubusercontent.com/23513723/63122038-205db800-bfa6-11e9-8453-4a3113c0f166.png)
will display an orange square in the Archive tag page.
Something like this would be better:
![download](https://user-images.githubusercontent.com/23513723/63121966-fdcb9f00-bfa5-11e9-9a1c-538843cf9f25.png)

**Comment by godofredoninja** [comment]
Hi @stephanefr 

All the images are centered. 

I think the solution is to align your images to the left side. 

- To do this you have to add styles in the tags page. `Code Injection -> Page Header`

```html
<style>
.topic-items .story-img { 
    object-position: left;
    -o-object-position: left;
}
</style>
```

- This solves that little problem. 

---

### When doing this the image has a low quality

To solve this you have to edit the following file. `custom-archive-tags.hbs`

https://github.com/godofredoninja/Mapache/blob/bd89c4c4b096df7300593d5de33bc72d362f841b/custom-archive-tags.hbs#L15

- Delete line 15 and paste the code below

```hbs
{{#if feature_image}}
    <img class="story-img u-absolute0 u-image u-block lazyload"
        src="{{img_url feature_image size="m"}}"
        srcset="{{img_url feature_image size="xxs"}}"
        data-srcset="{{img_url feature_image size="s"}} 300w,{{img_url feature_image size="m"}} 600w,{{img_url feature_image size="l"}} 1000w,{{img_url feature_image size="xl"}} 2000w"
        data-sizes="(max-width: 1000px) 100vw"
        alt="{{title}}"
    />
{{else}}
    <div class="u-absolute0 u-bgCover u-block" style="background-image:url({{asset "images/not-image.jpg"}})"></div>
{{/if}}
```
