### ISSUE TITLE
Support for commento.io

### ISSUE THREAD

**Issue by cerf203** [godofredoninja/Mapache#109]
Commento.io is a very good alternative of comments for disqus and facebook, especially when talking about privacy issues and apparently I am not the only user of raccoon who has requested this, there is some way to add this comment system to raccoon ? In the future could support be added as they do with disqus?
Remember that commento.io is faster than other comment systems and respects privacy.

**Comment by godofredoninja** [comment]
Hi @cerf203  :smile: 

For the next version I will add support for commento.io 
But changing in Mapache is very easy. 

- Add this code in the next line

```html
<div id="commento"></div>
```

https://github.com/godofredoninja/Mapache/blob/bd89c4c4b096df7300593d5de33bc72d362f841b/partials/article/article-comments.hbs#L10

- Add the following code with your settings. First you have to read the documentation of [commento.io](https://docs.commento.io/installation/self-hosting/embed-on-your-website/#embedding-commento)

```html
<script>
document.querySelectorAll('.post-comments-show').forEach(function (i) { i.classList.remove('u-hide') })
</script>

<script defer src="http://commento.example.com/js/commento.js"></script>
```

https://github.com/godofredoninja/Mapache/blob/bd89c4c4b096df7300593d5de33bc72d362f841b/partials/article/article-comments.hbs#L20-L58

- Replace all this code with this 

```hbs
{{t "Comments"}}
```
 

https://github.com/godofredoninja/Mapache/blob/bd89c4c4b096df7300593d5de33bc72d362f841b/partials/article/article-body.hbs#L24-L28

**Comment by godofredoninja** [comment]
Hello :smile: 

https://github.com/godofredoninja/Mapache/tree/cesar-reyes

I just created a branch for you. making such a modification. if you have any problem leave me in the comments.
