### ISSUE TITLE
Search on Firefox Mobile (Android) scrolls to the top 

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#11]
If I use the search feature with Firefox Mobile for Android the browser scrolls completely to the top. Tested on Smartphone and Tablet. Doesn't happen with Chrome. 
Maybe possible to fix?

**Comment by godofredoninja** [comment]
Please you can make a screenshot.

browsers supports Mapache
[http://caniuse.com/#search=flex](http://caniuse.com/#search=flex)

**Comment by MaluNoPeleke** [comment]
It is hard to make a screenshot because as soon as I click on the search icon the browser automatically scrolls up to the top and then it is possible to input search entries. 
This doesn't happen with Chrome but with Firefox for Android

**Comment by godofredoninja** [comment]
this is what I have in Firefox browsers for android
and I do not detect problems

---

![Imgur](http://i.imgur.com/RvwCM6W.jpg)

**Comment by MaluNoPeleke** [comment]
I have created a short video to demonstrate the issue: https://youtu.be/cyX2UgOOgo4
