### ISSUE TITLE
[Question] Will be Ghost v3 supported?

### ISSUE THREAD

**Issue by megazloj** [godofredoninja/Mapache#113]

**Comment by godofredoninja** [comment]
Hi @megazloj 

OMG :cry: 

At the moment Mapache does not support Ghost version 3

I hate my Life - Oh, my God, give me more time. :pray: 

But this week I'll finish updating. 

To have one of the best themes for Ghost.

**Comment by megazloj** [comment]
@godofredoninja I'm not pushing on you in any way! You're doing a great job and I'm looking forward to update Ghost version along with your awesome theme ;)

**Comment by cmilanf** [comment]
Take your time! We will remain with latest version 2 until Mapache supports version 3 :)

**Comment by godofredoninja** [comment]
Thank you :smile: 

In my free time, I'm making modifications to the theme

I make a screenshot of the things I'm doing

I think it'll be ready by Wednesday.

![localhost_2368_signup_](https://user-images.githubusercontent.com/10253167/67614343-2f6c9d80-f781-11e9-871a-2f68f6c2478e.png)
![localhost_2368_topics_](https://user-images.githubusercontent.com/10253167/67614345-2f6c9d80-f781-11e9-89ed-88c501623943.png)
![localhost_2368_about-us_ (1)](https://user-images.githubusercontent.com/10253167/67614387-d6513980-f781-11e9-95f4-3e587c3b2ffa.png)
![localhost_2368_team_](https://user-images.githubusercontent.com/10253167/67614347-30053400-f781-11e9-980d-bf2b04d3c619.png)
![localhost_2368_contact-mapache_](https://user-images.githubusercontent.com/10253167/67614348-30053400-f781-11e9-80fb-3e65c43652e8.png)
![localhost_2368_tag_pro_](https://user-images.githubusercontent.com/10253167/67614427-760ec780-f782-11e9-972d-1665cb4c2018.png)

**Comment by cerf203** [comment]
I'm watching the screenshots and you see a great update for the topic, I'm really excited and anxious.
There is no doubt that mapache is one of the best themes for ghost, much success @godofredoninja

**Comment by cerf203** [comment]
Is there any approximate release date?

**Comment by godofredoninja** [comment]
Sorry it took so long to update.

If you detect errors please tell me.
