### ISSUE TITLE
Featured posts in version 3.1.0

### ISSUE THREAD

**Issue by cmilanf** [godofredoninja/Mapache#115]
After upgrading to version 3.1.0 I am really missing the Featured Posts widget that used to sit along the Twitter and the Tags one. Has it been removed for some reason?

I am using the *Personal* template.

**Comment by godofredoninja** [comment]
:laughing: I think I eliminated. Because it took me a long time to load. 

But for the next version I'll add. Again.

**Comment by cmilanf** [comment]
Thank you Godofredo, it was a good thing because I could put at sight what I consider the most important articles I wrote. I will stick around with Ghost 2.37.0 for a little longer. I will keep an eye on it.

**Comment by godofredoninja** [comment]
I just updated the theme and it's back the featured articles in the sidebar

**Comment by StarWar** [comment]
@godofredoninja Would it be possible to make featured posts sticky and show first instead of the recent posts like the most other themes for ghosts do. How did you make the post sticky in your own blog at https://godofredo.ninja/?
