### ISSUE TITLE
Feature suggestion: configurable date format

### ISSUE THREAD

**Issue by cmilanf** [godofredoninja/Mapache#117]
Every time I upgrade the Mapache theme, I perform a small modification os the dates on the posts are absolute (1st December 2019) instead of relative (7 days ago). It would be nice if this could be configurable via the Site Footer customization.

The Mapache with Ghost 2.37.0 at [my site](https://calnus.com) shows this behavior.

**Comment by godofredoninja** [comment]
:thinking: 

I think you want something like this.

I'm making some small improvements to the Mapache theme.

Like the change from pink to blue


![Selección_006](https://user-images.githubusercontent.com/10253167/70591765-39b5f000-1ba5-11ea-9a5d-8679656b3496.jpg)

**Comment by cmilanf** [comment]
That's right, I like way more absolute dates rather than the relatives ones. I guess each user has his own taste. Ghost allows both, so it would be nice to be configurable.
