### ISSUE TITLE
Feature suggestion: configurable number of post tags at index page

### ISSUE THREAD

**Issue by cmilanf** [godofredoninja/Mapache#118]
A modification that I always do after Mapache upgrade is to show a certain number of tags in the post index page, usually the first three. By default Mapache shows only the first one, behavior that it's ok, but it would be nice to be configurable.

**Comment by godofredoninja** [comment]
:arrow_right:  You just have to uncomment this line of code

https://github.com/godofredoninja/Mapache/blob/c193532b6033648df13203d659051db7ff0e15fc/partials/helper/helper-story-meta.hbs#L3-L6

:arrow_right: And comment on the following line of code.

https://github.com/godofredoninja/Mapache/blob/c193532b6033648df13203d659051db7ff0e15fc/partials/helper/helper-story-meta.hbs#L9-L12

**Comment by cmilanf** [comment]
Great! Thank you godofredo!
