### ISSUE TITLE
Soporte para commento.io

### ISSUE THREAD

**Issue by cerf203** [godofredoninja/Mapache#119]
Commento.io es una muy buena alternativa de comentarios para disqus, especialmente cuando se habla de problemas de privacidad ¿hay alguna forma de agregar este sistema de comentarios a mapache?
Recordemos que commento.io es más rápido que otros sistemas de comentarios y respeta la privacidad.
Saludos y excelente trabajo en la nueva versión de mapache para Ghost 3.x.

**Comment by godofredoninja** [comment]
### Hey, Hola :smile: 

Es facil de cambiar tu sistema de comentarios. 

:arrow_right:  Tienes que remplazar todo esto

https://github.com/godofredoninja/Mapache/blob/c193532b6033648df13203d659051db7ff0e15fc/partials/article/article-comments.hbs#L1-L58

:arrow_right: Por este Codigo de aqui.

```hbs
<div id="post-comments" class="post-comments u-sizeFullWidth post-comments-show u-absolute0 u-fixed">
    <div class="post-comments-header u-paddingLeft15 u-flexCenter">
        <div class="js-toggle-comments button button--dark button--circle"><svg class="icon"><use xlink:href="#icon-close"></use></svg></div>
    </div>

    <div class="post-comments-wrap u-padding15">
        <div id="commento"></div>
    </div>
</div>

<div class="post-comments-overlay u-absolute0 u-fixed js-toggle-comments"></div>

{{#contentFor "scripts"}}
<script src="https://cdn.commento.io/js/commento.js" async defer></script>
<script>
    function readyComments() {
        var commentShow = document.querySelectorAll('.post-comments-show');
        commentShow.forEach(function(item){item.classList.remove('u-hide')});

        // Toggle Comments
        var toggleComments = document.querySelectorAll('.js-toggle-comments')
        toggleComments.forEach(function(item) { item.addEventListener('click', function (e) {
            e.preventDefault();
            document.body.classList.toggle('has-comments');
        })});
    }

    window.addEventListener('load', readyComments, false);
</script>
{{/contentFor}}
```

:arrow_right: Tambien tienes que remplazar esto

https://github.com/godofredoninja/Mapache/blob/c193532b6033648df13203d659051db7ff0e15fc/partials/article/article-body.hbs#L26-L28

:arrow_right:  Por esto

```hbs
<div class="button button--large button--dark button--comment post-comments-show js-toggle-comments">
            {{t "Comments"}}
        </div>
```

**Comment by cerf203** [comment]
Excelente, gracias por el apoyo.

**Comment by capriciousduck** [comment]
Hey @cerf203 How did you get it to work? I am getting errors. And you too are using the Dec release, right?
