### ISSUE TITLE
Feature request: previous & next post links

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#12]
Could you please add previous & next post links to the end of a post?
The feature is available via the {{prev_post}} & {{next_post}} helpers:
https://themes.ghost.org/docs/prev_next_post

**Comment by godofredoninja** [comment]
according to theme design

where you want to add  prev_post}} & {{next_post}} 

I add to the next version

**Comment by MaluNoPeleke** [comment]
I would suggest between article subscribe and comments. Maybe also additionally a list of similar articles based on tags. 
My current solution works with floating overlay buttons and similar articles at the bottom but the floating icons could be confusing I guess: https://www.peleke.de/braun-rasierer-series-9-9075cc-im-test-vergleich-mit-philips-rq1175/

**Comment by godofredoninja** [comment]
I just added what you mentioned to me d28088ff455554d53ccad80ee7256007301ff226
