### ISSUE TITLE
Agregar anchor a pagina de potcast

### ISSUE THREAD

**Issue by cerf203** [godofredoninja/Mapache#120]
Note que se tiene el logo de rss en lugar del de anchor en la pagina de podcast por lo que decidí agregar dicho logo a la carpeta images en assets pero al actualizar la plantilla sigue sin aparecerme.
Incluso decidí borrar los logos de itunes y pocket casts de dicha carpeta y volver a subir la plantilla para actualizarla pero me siguen apareciendo las imagenes ¿a que se debe? ¿no se borran las imágenes subidas en la carpeta del theme? ¿Por que no me aparece el logo de anchor?
obviamente actualice el código html que se agrega para que aparezcan los logos de estos servicios, igual si lo modifico dicho codigo puedo quitar las images pero me surge la duda ¿nunca se borrar realmente esas imagenes de la plantilla?

**Comment by godofredoninja** [comment]
:sweat_smile: 

En tu Pagina de Podcast remplaza por esto

```html
<a class="button" href="https://anchor.fm/" style="background: #8940fa;">
    <img alt="RSS Icon" rel="presentation" src="https://d12xoj7p9moygp.cloudfront.net/images/anchor-logo-header.png" style="height:20px;margin-right: 0;">
  </a>
```

**Comment by godofredoninja** [comment]
Las imagenes esta en la  misma plantilla. asi que no se borra. si borras la plantilla o el tema. se eliminara esas imagenes. 

:rofl:  No me percate sobre el logo. Pero igual tu logo puedes subir a la pagina de ghost y luego copiar la url de la imagen y utilizarlo en link del podcast. asi de facil
