### ISSUE TITLE
How do you set the search to Tags? I haven't been able to figure this out.

### ISSUE THREAD

**Issue by bershatsky** [godofredoninja/Mapache#122]
Per Twitter, you said to message you here. I'm trying to set the default search to search for Tags. 

Thanks for your help!

**Comment by godofredoninja** [comment]
### Hello :smile: 

Just answer here. 

https://twitter.com/GodoFredoNinja/status/1206969337061359616

Here's all the code. This only allows searches of the tags. 

```html
<script>
var searchSettings = {
        key: 'your api key',
        url: 'https://demo.com',
        options: {
            keys: ['name'],
        },
        api: {
            resource: 'tags',
            parameters: { 
                fields: ['name', 'slug'],
                filter: 'visibility:public',
            },
        },
        
        template: function (result) {
            var url = [location.protocol, '//', location.host].join('');
            return '<a href="' + url + '/tag/' + result.slug + '/">' + result.name + '</a>';
        }
    };    
</script>
```

**Comment by godofredoninja** [comment]
The Mapache search is very powerful and fast. You can configure many things. for example, limit searches, search by title, search by description. filter certain contents. and many more things.

**Comment by godofredoninja** [comment]
### Answering your question here.

https://twitter.com/NoahBershatsky/status/1207087957603016705

To hide in the mobile version the buttons to share:

You have two options:

1. First option - Add a style to your ghost dashboard. `dashboard ->  Code injection  -> site header`

```html
<style>
    .post-share-mob {display:none}
    .h-cover-items:hover .h-cover-header{bottom:0}
</style>
```

2. Second option - Comment this line of code

https://github.com/godofredoninja/Mapache/blob/c193532b6033648df13203d659051db7ff0e15fc/partials/article/article-body.hbs#L21

**Comment by godofredoninja** [comment]
:thinking: 

[PhotoSwipe](https://photoswipe.com/) It looks good. I'll do my tests to add it in the following versions.

**Comment by godofredoninja** [comment]
## To have a title that says. Featured articles

In this line

https://github.com/godofredoninja/Mapache/blob/c193532b6033648df13203d659051db7ff0e15fc/godo-home-fashion-concept.hbs#L6

Add this

```html
<div class="u-marginTop20 u-marginBottom20 u-fontSize22 post-fluid u-container u-fontWeightBold">Featured Articles</div>
```

**Comment by bershatsky** [comment]
This is looking great!
