### ISSUE TITLE
The "follow" menu in the top right on a desktop

### ISSUE THREAD

**Issue by bershatsky** [godofredoninja/Mapache#123]
On mine, I have four social icons - they all work fine, but then there is a solid line under them and a blank space. It almost looks like the menu should just end at that line, but there's a lot of extra space. 

Is this an easy fix? Thanks again!

<img width="1792" alt="Screen Shot 2019-12-18 at 5 18 35 PM" src="https://user-images.githubusercontent.com/9592543/71136714-8491c200-21ba-11ea-9683-fb935ebfe976.png">

**Comment by godofredoninja** [comment]
Hello.

 Below is the subscription box.

![Screenshot_20191218_223403](https://user-images.githubusercontent.com/10253167/71143028-1ca5a080-21e7-11ea-937a-5b4a0aca8b41.png)

If you want to remove that line you only need a little styles.

```html
<style>
.drop-border {
    border-bottom: 0;
    padding-bottom: 0;
    margin-bottom: 0;
}
</style>
```

**Comment by bershatsky** [comment]
That worked great!
