### ISSUE TITLE
Get err

### ISSUE THREAD

**Issue by neoartdoo** [godofredoninja/Mapache#125]
Hi, so i decide to go live with your theme so i setup, start ghost production and then someware in logs i notice this

[2020-01-13 21:26:13] WARN {{#get}} helper took 344ms to complete

{{#get}} helper took 344ms to complete

Error ID:
    530efe00-364b-11ea-8d4d-23c39d46c080

Error Code: 
    SLOW_GET_HELPER

Details:
    api:          v3.[object Object].browse
    apiOptions: 
      filter: id:-5e1c307421f0960249df31d6
      limit:  5
    returnedRows: 5

so as i little knowing ghost {#get} culd load al database :D And we need to make more efficient. 

 (SLOW_GET_HELPER) suggests that your theme is using the get helper, and might be querying a lot of data - it took 344ms for the get query to finish. While not absolutely necessary, you might want to look at your theme and see where the get helper is used, and if you can make it more efficient.

**Comment by godofredoninja** [comment]
Hello @neoartdoo  

I'm using the `{{#get}}` helper to get the following data.

- 5 featured articles for the home page sidebar
- 5 last articles for the post sidebar
- 6 Related Articles

This may generate the `slowHelper`. The log is generated when it exceeds `200ms`

Here it is mentioned.
https://github.com/TryGhost/Ghost/pull/10779

Also in the forum
https://forum.ghost.org/t/how-to-optimize-get-helper-and-reduce-ttfb/11022

One way to solve this is to call the data using the Ghost API and not use the `{{#get}}` ghost helper

:smile:  For the next version I will try to solve that little problem and make the theme faster.

**Comment by neoartdoo** [comment]
that will be nice :) 
yeah big sites that culd be a big problem for me i have 1500 articles so every time loading all then cut
And one more thing, 
maybe it is better to put uncompressed main.css for the little twiks. i create additional and some things just overwrite in code injection.

**Comment by prandelicious** [comment]
Been looking for the uncompressed CSS but couldn’t find it. Would be good if you also provide an uncompressed CSS. Thanks!

**Comment by godofredoninja** [comment]
Hi @prandelicious 

The development code is in the dev branch.
Please don't hate me for my code... I know my code is a little dirty. I'll soon reorganize everything.

https://github.com/godofredoninja/Mapache/tree/dev
