### ISSUE TITLE
instagram.pixelunion.net service seems to be down

### ISSUE THREAD

**Issue by valentierra** [godofredoninja/Mapache#129]
Hi There,

I was trying to get the Instagram Feed Token but received the following instead:

_This XML file does not appear to have any style information associated with it. The document tree is shown below._ (...)

Is there any other way to enable this Instagram feature?

**Comment by godofredoninja** [comment]
### Hello :nerd_face:  

Thank you for reporting this problem.

What's happening is the change in the Intagram API

Later on I will update it with the new API provided by Instagram

**Comment by godofredoninja** [comment]
Mapache stopped using instagram feed
