### ISSUE TITLE
Public posts visible as member only

### ISSUE THREAD

**Issue by tonyszko** [godofredoninja/Mapache#130]
I have an issue with this template - every public post I create is visible as a subscribers only.  Is there anything I'm missing in the settings of the theme?

**Comment by godofredoninja** [comment]
Hello

How are you?

I think this problem is in your Ghost settings

![Screenshot_2020-03-26 Settings - Labs - Kusi Doc](https://user-images.githubusercontent.com/10253167/77665966-5c022c80-6f4e-11ea-80a3-d67540dd4240.png)

**Comment by tonyszko** [comment]
I've found similar issue on Ghost forum - https://forum.ghost.org/t/solved-all-posts-behind-either-a-subscription-banner-or-paywall-even-public-ones-what-have-i-done-wrong/11795/8 - going over it with Ghost support at the moment. 

If it will be something related to the theme  I will report it back here.

**Comment by tonyszko** [comment]
It was Ghost issue - post with title only and no content is being show as a "members only" and it was a test post with no content :)

**Comment by godofredoninja** [comment]
:nerd_face: Hello @tonyszko 

This means that it is already solved. 

Then you can close this issue.
