### ISSUE TITLE
Dark mode only 🌑

### ISSUE THREAD

**Issue by liebling-love** [godofredoninja/Mapache#134]
Hey! 👋😃 I am a very beginner level front end dev, I love to learn new things. I am designing a small personal blog for me and I am using your theme it is literally very amazing theme 😍. I was thinking about if there is any way that we can enable **dark mode only** 🌑. Please navigate me.
Thank you! ❤️

**Comment by godofredoninja** [comment]
Hello :nerd_face: 

Thank you for using my theme 

Replace the code here and the dark mode will be activated

`<html lang="{{@site.lang}}" data-theme="dark">`

https://github.com/godofredoninja/Mapache/blob/b826555422a9069b58ac95714b324bb9f066fa9a/default.hbs#L10

**Comment by liebling-love** [comment]
Thank you so much!❤️
It worked ;)
