### ISSUE TITLE
Set Site Default for Light Mode / Dark Mode 

### ISSUE THREAD

**Issue by natehouk** [godofredoninja/Mapache#139]
Is there a way to set the site default for light mode / dark mode? I didn't see anything in the documentation.

**Comment by tylwright** [comment]
I, also, would love to set a default!

**Comment by tylwright** [comment]
Figured it out!  Place this in your site's footer (code injection):
```
<!-- Set dark mode with mapache -->
<script>
    function dark () {
        localStorage.setItem("selected-theme","dark");
    }
    
    dark();
</script>
```

**Comment by natehouk** [comment]
I believe the way you are doing it above would prevent the user from choosing an override choice.

This worked for me code injected into header, and doesn't prevent the user from setting their own choice:

```
<script>
  document.documentElement.setAttribute('data-theme', 'dark')
</script>
```
