### ISSUE TITLE
followSocialMedia additions not showing up with code injection

### ISSUE THREAD

**Issue by zombodotcom** [godofredoninja/Mapache#151]
I cannot see the follow parts i added 

![image](https://user-images.githubusercontent.com/13477955/92852981-8b95db80-f3ac-11ea-8080-9e02401d0c46.png)
![image](https://user-images.githubusercontent.com/13477955/92853018-9486ad00-f3ac-11ea-80fd-999fe459e3f5.png)

yes it is in the footer

**Comment by godofredoninja** [comment]
I think the regular expression to validate the URL is failing.

The momentary solution may be to add your link to a link shortener. 

for example:

- https://bitly.com/
