### ISSUE TITLE
Search icon hidden

### ISSUE THREAD

**Issue by sultonov** [godofredoninja/Mapache#154]
https://github.com/godofredoninja/Mapache/blob/b826555422a9069b58ac95714b324bb9f066fa9a/partials/header.hbs#L95

Search item not showing in the header, when, we remove class u-hide from classes list, it doesn't work - doesn't opening modal

**Comment by martip07** [comment]
You have to setup an integration app on your ghost blog then add this on your site footer:

`<script>
  var searchSettings = {
    key: 'ADD_YOUR_API_KEY',
    url: 'https://yourblogdomain',
  };
</script>
`
