### ISSUE TITLE
Instagram API fix

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#159]
The Instagram API doesn't seem to work anymore:

> Access to fetch at 'https://api.instagram.com/v1/users/30638753/media/recent/?access_token=30638753.a941e97.c0508dbd63f84b44aef9d22cc4936c62&count=10&callback=?' from origin 'https://www.peleke.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This seems to be [discussed already](https://github.com/sugarshin/react-instagram-embed/issues/89). Any way to fix this?

**Comment by yichnal** [comment]
hit by this ?
https://support.pixelunion.net/hc/en-us/articles/360041460554-Important-notice-Instagram-feed-removal

**Comment by godofredoninja** [comment]
Mapache stopped using instagram feed
