### ISSUE TITLE
I need suggestions to improve the theme

### ISSUE THREAD

**Issue by godofredoninja** [godofredoninja/Mapache#164]
In my spare time I will start to improve the Mapache theme. 

And I need your suggestions or your ideas to add it as I progress in the development.

**Comment by ElderMael** [comment]
Hi, I have a sugestion:

Can you somehow disable the newsletter (or other parts of the template) with feature flags just like you did on injection headers?

I have a ghost blog using your theme and I would love to disable this as I already have a newsletter outside the blog.

**Comment by WatsonJH** [comment]
Hey, 

Glad to hear you want to improve it. I love your theme.

One Improvement I would love to see, is an update of the code syntax highlighting, to have it look like the 2 exemples below.
The first one you have the line numbers, and HTML icon and tag on the top right with a copy button
![image](https://user-images.githubusercontent.com/70151852/117364370-d3adc500-ae8b-11eb-960f-cedf053f155b.png)
For this one, it's to differentiate input/output on a terminal.
![image](https://user-images.githubusercontent.com/70151852/117364427-e1634a80-ae8b-11eb-9959-54cedf6f7ce8.png)

Another improvement, would be for the featured article list on the right sidebar. I know in the back end we can assign a colour to a tag, it could be nice if the accent colour next to the number takes the one from the main tag of the article.

**Comment by WatsonJH** [comment]
Another improvement, a feature that show your progress as you read through an article, to easily let you know how far you have read through it.

**Comment by tudomuonnam** [comment]
Hi @godofredoninja 

I'm newbie with blog and then I discover ghost and Mapache. It worked great! Thanks alot

But now I see a problems, news ghost cms 4.0 have features "Public preview" allows add lines if half of content requires user login. I tried it but not success. Mapache block user from begining, not half of content.
Here are another thread about it: https://forum.ghost.org/t/helper-for-new-public-preview-content/20761
Can you fix it? Thanks

**Comment by MaluNoPeleke** [comment]
What about multi-language toggle? It seems to be possible with some effort: https://forum.ghost.org/t/ghost-multi-language-theme-custom-dev-experience/23588

**Comment by softhints** [comment]
I would like to have a new page with posts per tag like these there:

Ghost ease: https://ease.ghost.io/

Having last N articles per tags as a home page.
