### ISSUE TITLE
Load fonts a bit faster (patch included)

### ISSUE THREAD

**Issue by yichnal** [godofredoninja/Mapache#165]
In default.hbs, include :

`    <link rel="preconnect" href="https://fonts.gstatic.com/">
`
on top, in the area described as
`    {{!-- Fonts => Roboto && Merriweather --}}
`

**Comment by godofredoninja** [comment]
Hello @yichnal 

I am thinking of changing the typography for the titles.

But I still can't decide which typeface to use.

The typefaces to be chosen so far are:

1.  [Inter](https://fonts.google.com/specimen/Inter)
2. [Public Sans](https://fonts.google.com/specimen/Public+Sans)
3. [Poppins](https://fonts.google.com/specimen/Poppins)

For the content I have not yet chosen the typography.

I await your suggestion

**Comment by WatsonJH** [comment]
I like option 2 :)

**Comment by yichnal** [comment]
Option 2 : Public Sans

**Comment by MaluNoPeleke** [comment]
Public Sans
