### ISSUE TITLE
Tag cloud appears with strange color

### ISSUE THREAD

**Issue by hassan-elamir** [godofredoninja/Mapache#166]
HI,
Can you please change the tag cloud appearance.
Currently it is shown like this.
![image](https://user-images.githubusercontent.com/83805153/117405295-a3d0e280-aec8-11eb-8b4a-1cf4dc6dc0c1.png)
I was expecting it to show like this
![image](https://user-images.githubusercontent.com/83805153/117405434-dc70bc00-aec8-11eb-9b62-e82808e2f4e8.png)
Thank you.

**Comment by godofredoninja** [comment]
Hi.

In this version the buttons have changed.
