### ISSUE TITLE
multilingue (more than one language website)

### ISSUE THREAD

**Issue by JOduMonT** [godofredoninja/Mapache#168]
Hi;
I saw your theme could be use in different language and it work well, but how I could use is for a bilingual website ?
such as having content in English and content in French on the same website.

`Settings -> General -> Publication Language` I tried
`fr,en` and `fr;en` and `fr` en but only when I try fr the website appear in french

**Comment by MaluNoPeleke** [comment]
It seems to be possible in general but hard to achieve: https://forum.ghost.org/t/ghost-multi-language-theme-custom-dev-experience/23588

**Comment by rjulie95** [comment]
Hi,

You have this article to adapt your website in two or more language : https://ghost.org/docs/tutorials/multi-language-content/

**Comment by godofredoninja** [comment]
Hello.

In this version I added a button, but you have to add your links manually. 

At the moment it is a form to solve. 

https://github.com/godofredoninja/Mapache/blob/master/docs/custom-theme-settings.md#multi-language

**Comment by rjulie95** [comment]
Thank, just a litte remark you wrote this : /partials/layout/heder.hbs your forgot the "a" in header.hbs

**Comment by godofredoninja** [comment]
Lol

So, it's no use writing code when your heart is broken.

🤣
