### ISSUE TITLE
Disablement of member functionality not removing login / signup button functionality.

### ISSUE THREAD

**Issue by AKG152** [godofredoninja/Mapache#171]
Hi,

With the member functionality turned off as per docs this should remove the sign up / sign in functionality however this remains on the website.

Any thoughts about how to remove this as my site is free and I just want it for newsletter sign ups.

Thanks.

**Comment by godofredoninja** [comment]
Hello.

Here in the documentation I added how you can disable

https://github.com/godofredoninja/Mapache/blob/master/docs/custom-theme-settings.md#membership
