### ISSUE TITLE
The gallery does not open the images in large

### ISSUE THREAD

**Issue by rjulie95** [godofredoninja/Mapache#173]
Hi,

I use Ghost 4.32 and Mapache 4.0

When the Gallery button is disabled, when I click on the image, nothing happens
When the gallery button is on, when i click popup only a small image

See exemple here : https://www.en-voyages.fr/baringo-the-lake/

For me it's a huge regression than the other version of mapache 

Do you have a solution ?

Thank

**Comment by rjulie95** [comment]
I switch to old version 3.1.3, a this time version 4.0 it's not good for me

**Comment by godofredoninja** [comment]
Hello.

I just tested and the gallery works correctly.

The problem is that not everyone wants to have a gallery, that's why I have added a switch so that it can be activated and deactivated.

I am using a lighter version of the library so that it can be loaded faster.

**What don't you like about this new version of Mapache?** I need to know so I can improve.

😄

**Comment by rjulie95** [comment]
Hello,

Now I put on my site the version 4.0 of Mapache, please check the gallery and click on an image, is the result normal for you?

https://www.en-voyages.fr/baringo-the-lake/

When your test is finished, I will switch to an older version of Mapache and you will see the difference.

**Comment by godofredoninja** [comment]
It is working fine 🤔 

https://gifyu.com/image/SScHU

**Comment by godofredoninja** [comment]
I need to tell you something.

Gallery is disabled for mobile devices.

The reason why I deactivated on mobile devices is to speed very fast.

**Comment by rjulie95** [comment]
I think we don't understand each other

In version 4.0 when you click on the first picture, you have a small image correct ?

I just revert on version 3.1.3

I you click on the first picture, you see a large image (i test on computer not on phone)

Can you see the difference ?

would it be possible to have the same behavior with version 4 ?

Thank

**Comment by rjulie95** [comment]
No news for this bug ?

**Comment by rjulie95** [comment]
> **What don't you like about this new version of Mapache?** I need to know so I can improve.

Hello,

For me Gallery is very important, it's possible to implement all function of 
lightGallery in version 4?

Thank

**Comment by godofredoninja** [comment]
🤔 

Hi.

Here is the previous gallery

[mapache-v4.0.0.zip](https://github.com/godofredoninja/Mapache/files/7796683/mapache-v4.0.0.zip)

**Comment by godofredoninja** [comment]
Here tag

https://github.com/godofredoninja/Mapache/tree/lightgallery-1.1.3

**Comment by rjulie95** [comment]
Nice thank you and happy new year
