### ISSUE TITLE
Text with URL in lgiht mot not visible 

### ISSUE THREAD

**Issue by rjulie95** [godofredoninja/Mapache#174]
Hi,

Hello in Mapache 4.0 not in light mode the link are not visible, in dark mode is correct : https://www.en-voyages.fr/baringo-les-interactions/

Thank

**Comment by godofredoninja** [comment]
In your ghost settings, you can play with the colors.

![image](https://user-images.githubusercontent.com/10253167/147881458-141f9963-08ae-490b-82af-f8ca7de82ea0.png)

**Comment by rjulie95** [comment]
Thank
