### ISSUE TITLE
Add more languages to Prism

### ISSUE THREAD

**Issue by cmilanf** [godofredoninja/Mapache#22]
Is it possible to add more languages for Prism syntax highlight? It looks like only a subset is provided.

**Comment by cmilanf** [comment]
I modified the Prism code in bundle.min.js in order to include the Autoloader plugin (http://prismjs.com/plugins/autoloader/). With this, Prism is able to load on-demand required language javascript code without making the file larger. Godofredo, consider including this in the theme, that... by the way, I just love it :)

**Comment by credmp** [comment]
Could you submit a pull request for it? I would like to add it as well.

It would be good if the theme would come with a script that allows you to add your own prims configurations.

**Comment by cmilanf** [comment]
You can see the mod in my fork of the Mapache (https://github.com/cmilanf/Mapache/tree/karloch/assets/js), but of course it is better to submit a pull request :)

**Comment by godofredoninja** [comment]
Hi People.

now has syntax supports the all prism

e2c858a63150a95aeb8e0cfa0fa3da7ae787f5ea
