### ISSUE TITLE
"Load More" Button isn´t working

### ISSUE THREAD

**Issue by hpz24** [godofredoninja/Mapache#24]
Hi, 
thanks for your cool themes, i like it very much, but i have a few problems:
- If i press the "Load More" Button on the site, the button circles and nothing happens. No error - no result.
- Searchbox finds results, but a klick on it brings an 404. I´m using the blog in a subdomain and the search result are without the path for the subdomain. How can i change that?

Thanks for help, 
hanspeter

hpz.eu/blog
Ghost 0.10.1

**Comment by anonymouce** [comment]
Loadmore Not Working . I have a CNAME flattened blog  , myblog.rhcloud.com => myblog.com. It fails on myblog.com but works on  myblog.rhcloud.com

**Comment by godofredoninja** [comment]
Thank you for using my theme Mapache.

In the next version I will fix errors subdomains.

please if you want a fast solution shares the URL of your page

**Comment by anonymouce** [comment]
Great theme! 
http://y2kdesignworks.com/

http://nodejs-y2kdesignworks.rhcloud.com/

**Comment by zxt50330** [comment]
I also have this problem.
'Can't find variable: fetch' 194:74 bundle.min.js
Ghost 0.11.0

**Comment by glodinas** [comment]
My too !! Ghost 0.11.1

**Comment by 110EIm** [comment]
I have same issue on my blog.
It doesn't work only at iOS. PC and Android are work successfully.
I've tested it with safari and chrome on iOS, but neither work well. It just spins all day long.

**Comment by godofredoninja** [comment]
Hi @110EIm   😄
Thanks for using my theme for ghost.

I do not actually test for IOS Because I do not have the device

— For the next version I hope to improve all the errors you are mentioning
— I will also improve in performance

**Comment by vegasbrianc** [comment]
I tried looking for the issue with the IOS loading. It appears the fetch variable is not defined and or not imported. I'm still looking. Here's the IOS errors from Safari. 
<img width="1278" alt="screen shot 2016-12-05 at 23 12 42" src="https://cloud.githubusercontent.com/assets/674790/20904569/6ab19844-bb40-11e6-907f-e3ffa0637059.png">

**Comment by vegasbrianc** [comment]
Hi @godofredoninja I did a lot of research why fetch is not working. It appears Safari/IOS do not support fetch as of now. I've been looking at other tools but everything seems to add a lot of bloat. Any ideas?

https://github.com/github/fetch/issues/302

**Comment by godofredoninja** [comment]
@vegasbrianc  Thanks for showing the error in about two days I solve it

**Comment by godofredoninja** [comment]
@vegasbrianc I think it works now. Because I'm using jQuery to perform the call via Get
