### ISSUE TITLE
url_regexp doesn't work for Google+ URLs

### ISSUE THREAD

**Issue by tdack** [godofredoninja/Mapache#25]
The regex used to determine if a URL is valid doesn't work for Google+ URLs like `https://plus.google.com/+SergyBrin`

Original: `url_regexp = /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/`

Working: `url_regexp = /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \+\.-]*)*\/?$/`

Just a matter of adding `\+`.

**Comment by godofredoninja** [comment]
Thank you for your contribution.
This version already has added

3266cf5
