### ISSUE TITLE
Very long loading times with 2.0.4 and Disqus

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#26]
With the new version 2.0.4 I observe very long loading times until the website can be used. I had to switch back to 2.0.3 to get rid of them. The whole browser is unusable in this time (~10 seconds).
Do you know how to solve it? It works as expected with Facebook comments.
Thanks

![disqus](https://cloud.githubusercontent.com/assets/1446541/19014152/6d5f1316-87e5-11e6-9af4-57a012386427.jpg)

**Comment by godofredoninja** [comment]
I have now added a way to load in async mode  d762b40697383bc10a016f7bb87cd357072dd3a3
