### ISSUE TITLE
Sidebar jumps to top and is completely broken

### ISSUE THREAD

**Issue by EpicLPer** [godofredoninja/Mapache#30]
Am I doing something wrong here or is this a bug? I'm hosting the site on Ghost directly (for the test-period only).

I've added this to the blog header already:
`<div class="sidebar-items">`
    `<div class="fixed">`
      ` ... your content fixed ...`
    `</div>`
`</div>`

![stkern_2016-11-24_085003](https://cloud.githubusercontent.com/assets/8442196/20590396/1e0022b6-b223-11e6-93b2-29d86f3dbd1f.png)

**Comment by godofredoninja** [comment]
hello
how are you?

That piece of code is to add additional content in the sidebar

I could send the url of your site to be able to help you better 😃

**Comment by EpicLPer** [comment]
Thanks for the reply!

Here you go: http://epiclper.ghost.io/
Also another question: How do I add the social links to the "big header portion" like you show in the screenshots? That's one of the main reasons to choose this theme ;)

**Comment by godofredoninja** [comment]
Hello Bro.

— Please remove that piece of code you added blog header.
```html
<div class="sidebar-items">
<div class="fixed">
... your content fixed ...
</div>
</div>
```

## You have to read the documentation so you can configure

— for social links Facebook and Twitter

To be able to add facebook and twitter.
You have to do it directly in your ghost administration

**Comment by EpicLPer** [comment]
Heya,

thanks for the reply. But the documentation does nowhere say how to enable the sidebar, only how to add stuff. That said, I'm also pretty new to Ghost in general :)

**Comment by godofredoninja** [comment]
— Add your sticky content inside the sidebar `./partials/sidebar.hbs`  but at the end

 908bd94d7a893776b31f2c467ccf74931e9fc5f9

```html
<!-- Add sticky content to the bottom -->
<div class="sidebar-sticky">
  <h3 class="sidebar-title">...your title sticky ...</h3>
  ... your content sticky ...
</div>
```
