### ISSUE TITLE
Readme and License are contradictory.

### ISSUE THREAD

**Issue by JacobCWard** [godofredoninja/Mapache#32]
The first paragraph says "[It is strictly forbidden commercial use.](https://github.com/godofredoninja/Mapache#free-theme-for-ghost)"

However, last [paragraph](https://github.com/godofredoninja/Mapache#copyright--license) and the [LICENSE file](https://github.com/godofredoninja/Mapache/blob/master/LICENSE) release the theme under the MIT license which has no restrictions on commercial use.

**Comment by dippersauce** [comment]
The README.md may say that commercial use is forbidden, but  in a legal setting the license would almost always take precedence.
