### ISSUE TITLE
Sidebar no longer fixed

### ISSUE THREAD

**Issue by adeleglise** [godofredoninja/Mapache#33]
Hi, first of all thanks a lot for this theme !

I've just pulled the repo to have uptodate files.

My sidebar fixed items are not fixed anymore, how can I solve this ?

**Comment by adeleglise** [comment]
Hi, any news on this one ?

**Comment by godofredoninja** [comment]
## Excuse me I do not have much time to work 

— Add your sticky content inside the sidebar `./partials/sidebar.hbs`  but at the end

 908bd94d7a893776b31f2c467ccf74931e9fc5f9

```html
<!-- Add sticky content to the bottom -->
<div class="sidebar-sticky">
  <h3 class="sidebar-title">...your title sticky ...</h3>
  ... your content sticky ...
</div>
```
