### ISSUE TITLE
[Suggestion] Short post format?

### ISSUE THREAD

**Issue by bgiesing** [godofredoninja/Mapache#37]
I think it would be pretty cool to add a short post format that would not show the description and show only the title, a smaller thumbnail, and add some icon to say it's a short post when displayed on the homepage which would be useful for small update posts.

Here's an example of what I mean (this is from Android Police):
![Post Example](http://i.imgur.com/ZPFPCe6.png)

**Comment by godofredoninja** [comment]
Hi.
— You can send me the url of the reference page to be able to analyze it

— If you are looking for a very simple theme I just created one and it is very elegant
[https://github.com/godofredoninja/simply](https://github.com/godofredoninja/simply)

**Comment by bgiesing** [comment]
Well the post itself uses the same format as any normal post would, it would just change how the article on the homepage/tag pages look so it's hard to link to an exact page to reference.

Anyway this might work (you might have to scroll back to see it if it's not on top by time you get to it) http://www.androidpolice.com/?s=android+pay

**Comment by godofredoninja** [comment]
Mapache — Is inspired by the following pages

.  [https://hypebeast.com/](https://hypebeast.com/) => entry and post
. [https://thenextweb.com](https://thenextweb.com/business/2017/02/19/three-tech-founders-on-scaling-multi-million-dollar-businesses) => share
. [https://firebase.google.com/](https://firebase.google.com/) => menu
