### ISSUE TITLE
prismjs line-numbers

### ISSUE THREAD

**Issue by cmilanf** [godofredoninja/Mapache#38]
It looks like since the update to use the autoloader, the line-numbers stopped working. I was not able to find the plugin in the code so I think this needs to be added somewhere.

```
function(){"undefined"!=typeof self&&self.Prism&&self.document&&Prism.hooks.add("complete",function(e){if(e.code){var t=e.element.parentNode,s=/\s*\bline-numbers\b\s*/;if(t&&/pre/i.test(t.nodeName)&&(s.test(t.className)||s.test(e.element.className))&&!e.element.querySelector(".line-numbers-rows")){s.test(e.element.className)&&(e.element.className=e.element.className.replace(s,"")),s.test(t.className)||(t.className+=" line-numbers");var n,a=e.code.match(/\n(?!$)/g),l=a?a.length+1:1,r=new Array(l+1);r=r.join("<span></span>"),n=document.createElement("span"),n.setAttribute("aria-hidden","true"),n.className="line-numbers-rows",n.innerHTML=r,t.hasAttribute("data-start")&&(t.style.counterReset="linenumber "+(parseInt(t.getAttribute("data-start"),10)-1)),e.element.appendChild(n)}}})}()
```

**Comment by godofredoninja** [comment]
@cmilanf  👉 In the following update I will add it

**Comment by cmilanf** [comment]
Ah, do not forget the corresponding CSS, it was missing too :) By the way, not related to this issue, I would be happy to contribute with pull requests to the dev branch, but I don't know how to build the site through webpack; some reference in the dev's README.md would be very welcome :)

**Comment by godofredoninja** [comment]
Hello @cmilanf 

— This new version already includes the numbers for the lines 177b5268e313c4c8eca47eedf85fd9e22fd7e143
