### ISSUE TITLE
Missing space between "href" and "onclick"

### ISSUE THREAD

**Issue by radarsu** [godofredoninja/Mapache#4]
In post.hbs there is missing space between href and onclick tag:
(...) href="https://twitter.com/share?text={{encode title}}&amp;url={{url absolute="true"}}"onclick= (...)
And it should be:
(...) href="https://twitter.com/share?text={{encode title}}&amp;url={{url absolute="true"}}" onclick= (...)

**Comment by godofredoninja** [comment]
completed with revision 53ee572774a31e9f572c9363b4841512a6841fa1
