### ISSUE TITLE
On bottom of main page loading endlessly

### ISSUE THREAD

**Issue by Dittschinator** [godofredoninja/Mapache#43]
I set my site with 10 pages each. When I reach the bottom of the main page, and it most probably also occur in the other branches, it does say "loading", but there is no further progress. I doesn't load the next 10 articles and it does not show up to go on next page.

Maybe I am wrong? Thanks for help!

**Comment by godofredoninja** [comment]
Hello @Dittschinator 

— Please share your page to help you better

**Comment by Dittschinator** [comment]
Hi,

Sorry, there you go:

https://papas-bloggen.de

**Comment by godofredoninja** [comment]
@Dittschinator 

The following link can solve your problem — https://github.com/godofredoninja/Mapache/issues/29#issuecomment-268712184

**Comment by Dittschinator** [comment]
@godofredoninja 

Works perfectly! Thanks for your help!

BTW, this theme is great and I love it! Cheers!
