### ISSUE TITLE
Ghost 1.0 support 

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#44]
Is Mapache already compatible with the upcoming Ghost 1.0 update or do you have plans to make it compatible? 
Thanks!

**Comment by godofredoninja** [comment]
😄 
 Of course I will continue with the development.
I want the version 1 is stable to update Mapache

**Comment by godofredoninja** [comment]
Now Mapache supports ghost 1.0.0 8cff9f132f6709ba02aff8fbfabcd3ea86144d61

**Comment by MaluNoPeleke** [comment]
Thanks a lot!
