### ISSUE TITLE
Line numbers not working 

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#46]
I have installed Ghost 1.5.0 with Mapache 2.0.8 and everything is working fine except for the line numbers of Prism JS as you can see here: https://www.peleke.de/ghost-1-0-aktualisierung-bei-uberspace/
How can I make it work? 
Thanks in advance

**Comment by godofredoninja** [comment]
Hello @MaluNoPeleke 

Please read — https://github.com/godofredoninja/Mapache#prismjs-code-syntax

**Comment by MaluNoPeleke** [comment]
Hi @godofredoninja

I have done that and used ```bash line-numbers for the code snippet but the line numbers are not showing up.

**Comment by godofredoninja** [comment]
The problem comes from ghost.
At this moment I can not explain why this is happening.

I hope to investigate why it is happening later.

**Comment by godofredoninja** [comment]
— If you want to have the numbering. Just add this piece of code in your ghost configuration in the code section

```html
<script>
    $('pre').addClass('line-numbers');
</script> 
```

**Comment by MaluNoPeleke** [comment]
Great, working now! :)

**Comment by kawaiseb** [comment]
I add it in my code section but no way... line-numbers is never activated... any idea ?
