### ISSUE TITLE
Add more Video embeds to the Video Layout

### ISSUE THREAD

**Issue by bgiesing** [godofredoninja/Mapache#48]
I use Vid.me for my videos so it would be nice for the video layout to work with those.

Example embed code:

```
<iframe src="https://vid.me/e/DUiF?stats=1" width="1280" height="720" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen scrolling="no"></iframe>
```

**Comment by godofredoninja** [comment]
For the next update I will include support for vid.me

**Comment by godofredoninja** [comment]
The new version already supports
https://github.com/godofredoninja/Mapache/releases/tag/v2.0.9
