### ISSUE TITLE
Disqus comments in another language redundant 

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#49]
I have activated Disqus comments and changed the language strings in Disqus to German ("Kommentare") but Mapache shows "x Kommentare comments" instead of "x Kommentare". 
How can I get rid of the English "comments" in Mapache? 
Here is an example: https://www.peleke.de/ghost-1-0-aktualisierung-bei-uberspace/

**Comment by godofredoninja** [comment]
Hello @MaluNoPeleke 

— For the next version I resolve to have a better name of the comments

- Do you have any suggestions for improving the mapache theme?
I want to mapache to be an excellent theme for ghost

Please, help me

**Comment by MaluNoPeleke** [comment]
I would like to be able to use as much as possible German language strings. 
Currently I am modifying some strings with every theme update again. Would be great if I could use a static file for those things. 
In this specific case the defined strings from the Disqus settings should override the default string from the theme instead of adding "comments" to the Disqus string.

**Comment by godofredoninja** [comment]
Ghost does not exist a function to be able to have a better control of the language.
So far the only way is to edit the theme.

Now with this version of raccoon the comments will be better.

Please read the new documentation of raccoon

**Comment by MaluNoPeleke** [comment]
Thanks a lot
