### ISSUE TITLE
Sidebar smaller while scrolling

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#50]
I have a strange problem with the sidebar while scrolling: it seems to reduce the width in Chrome when I am actively scrolling.
Why is this a problem you may ask? Because the widget I use in that area doesn't fit anymore in that case and makes scrolling slower:
![scrolling](https://user-images.githubusercontent.com/1446541/29538847-cac4e17a-86c7-11e7-8eee-d8b1a5aa7a34.jpg)
Another small and strange issue is the fact that the widget won't be displayed if I remove the first line

     <script src="//assets.juicer.io/embed.js" type="text/javascript"></script>

Do you know why?

Are you able to fix that? 
URL: https://www.peleke.de/
Thanks in advance.

**Comment by godofredoninja** [comment]
— With the new version of Mapachethis problem is solved

**Comment by MaluNoPeleke** [comment]
Thank you very much!
