### ISSUE TITLE
Falta el logo de Telegram

### ISSUE THREAD

**Issue by danielperez9430** [godofredoninja/Mapache#52]
Una vez insertado el código:

var followSocialMedia = {

  'telegram':'https://...',

};

Con la url que hace referencia a un canal o grupo de Telegram. Guardo los cambios y a la hora de visualizarse no aparece el icono:

<a href="https://imgbb.com/"><img src="https://image.ibb.co/f0NfMv/falloo.png" alt="falloo" border="0"></a>

Uso la versión v2.0.9

**Comment by godofredoninja** [comment]
Hola.
Que tal como estas... 

Tengo una expresión para validar la URL

si esta mal una URL es posible que no le acepte

Prueba con un acortador de URL

por ejemplo => https://goo.gl/

**Comment by danielperez9430** [comment]
Ya funciona, muchas gracias :kissing_heart:
