### ISSUE TITLE
Open or Not ??

### ISSUE THREAD

**Issue by jodumont** [godofredoninja/Mapache#53]
in your README
`it is strictly forbidden commercial use. If you have any suggestions to improve the theme, you can send me tweet to @GodoFredoNinja`

in your LICENCE
`to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software`

**Comment by godofredoninja** [comment]
very soon I will change the license.

the project is free.

you can use modify but you have to distribute for free

This prohibited the sale

**Comment by jodumont** [comment]
thanks for the clarifcation :)
greate theme by the way!
