### ISSUE TITLE
Impossible to use prism

### ISSUE THREAD

**Issue by kawaiseb** [godofredoninja/Mapache#54]
Hi fredo, thanks for your template, nice job :) I'm trying now to use prism, but it does not work. I'm using v2.0.9. My blog is here : https://pagesjaunestech.ghost.io/. I saw all sources of prism in the zip file. Should I activate a particular conf for prism to work? Thanks a lot.

**Comment by godofredoninja** [comment]
Hello :) 

you are very right.
there is an error in the load.
I hope to correct for the next version

**Comment by kawaiseb** [comment]
Ok i think i found the problem, i migrated ghost to v1.8.4 and it works but not completly :(
For '''css style it works, but for '''java it does not :( Line numbers seems to be desactivated too.
ex which does not work : 

\'''java line-numbers
class Personne {
    var nom: String = "Dupont"
    var prenom: String = "Jean"
    var age: Int = 24
    var adresse: String = "94 rue machin"
}
'''

**Comment by godofredoninja** [comment]
Prism is loaded async, to make the page faster

— firts prism load css, javascript, html and after is async

— Line Numbers https://github.com/godofredoninja/Mapache/issues/46#issuecomment-324734592

**Comment by godofredoninja** [comment]
— already solved in the new version

https://github.com/godofredoninja/Mapache/blob/a2f4dd1429eadec2d8ce689787d09be50d6c4240/src/scripts/routes/post.js#L46
