### ISSUE TITLE
Gallery problem

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#55]
I have added featherlight gallery features via code injection to my page as [your suggestion](https://github.com/godofredoninja/Mapache/issues/40#issuecomment-314569514) but on [this specific page](https://www.peleke.de/fotos/) every image seems to stay for its own without being detected as one gallery.
How can I click on one of the images at that page and then use the featherlight gallery feature to cycle through them?
Thanks in advance for your support!

PS: I have asked for a solution at the [featherlight GitHub page](https://github.com/noelboss/featherlight/issues/319) but without success...

**Comment by danielperez9430** [comment]
This feaute coming to ghost soon with Koenig editor. Now is a exterimental feauture. Only wait. ;)
