### ISSUE TITLE
Feature request: Google translate integration

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#56]
Is it possible to add a small switch at the top (?) which enables Google translate for other languages?
It is not a perfect solution for multi language compatibility but easy to implement and flexible.

**Comment by MaluNoPeleke** [comment]
Now it is easy to add translation of the theme (not the content) easily:
https://themes.ghost.org/docs/i18n
Maybe you can add this to Mapache in one of the next releases as well.

**Comment by godofredoninja** [comment]
the new version of Mapache already supports for different languages
