### ISSUE TITLE
Link hover effect

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#57]
I would like to see some hover effect on links which I have achieved by adding the following code to the code injection:

`<style>
a:-webkit-any-link {
    text-decoration: none !important;
}
.container a:-webkit-any-link:hover {
    text-decoration: underline !important;
}
.container a:hover {
    text-decoration: underline;
}
</style>`

With this code links get underlined by hovering except for tags, where it should be inactive because of aesthetics but I don't know what code is needed for that.

See https://www.peleke.de/ as an example.

**Comment by godofredoninja** [comment]
```html
<style> 
    a:-webkit-any-link { text-decoration: none !important; } 
    .container a:-webkit-any-link:hover:not(.btn) { text-decoration: underline !important; } 
    .container a:hover:not(.btn) { text-decoration: underline; } 
</style>
```
