### ISSUE TITLE
Enhancements: Display estimated reading time

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#60]
With Ghost 1.17 [reading_time helper was introduced](https://themes.ghost.org/v1.17.0/docs/reading_time).
It would be nice to have this integrated in the next Mapache release at the top of a post.

**Comment by godofredoninja** [comment]
**You have more suggestions to improve the topic.**

**I want the Mapache to become one of the best ghost themes**

**Comment by MaluNoPeleke** [comment]
Thanks a lot!
