### ISSUE TITLE
Twitter feeds are not displaying

### ISSUE THREAD

**Issue by shubham0d** [godofredoninja/Mapache#66]
After updating to latest ghost version. inside the left side twitter column tweets are not displaying.
![twitter_issue](https://user-images.githubusercontent.com/12750163/35515746-f70d6b12-052f-11e8-97e3-6c57aa89d40e.png)
Only above thing is showing.

**Comment by danielperez9430** [comment]
It only happens to me if I am using the browser in incognit mode. Check that you do not have the active adbkock. I use the laster version of mapache and work perfectly :)

**Comment by danielperez9430** [comment]
Thanks you :)
