### ISSUE TITLE
Feauture Request: Amp theme in Mapache for mail

### ISSUE THREAD

**Issue by danielperez9430** [godofredoninja/Mapache#68]
Google lanzo hace 7 horas amp para soportar gmail o otras apps de mail. Seria posible que mapache lo integre??
https://www.blog.google/products/g-suite/bringing-power-amp-gmail/

https://github.com/ampproject/amphtml/issues/13457

**Comment by godofredoninja** [comment]
En las próximas versiones añadiré el soporte para GMAIL y con algunas mejoras  😀

**Comment by danielperez9430** [comment]
Este mensaje que acaba de llegar de Google. Vendrá también por el tema supongo?

 Search Console ha detectado que hay 2 nuevos problemas de Accelerated Mobile Pages en tu sitio web. Por este motivo, es posible que la experiencia de Accelerated Mobile Pages se vea afectada en los resultados de la Búsqueda de Google. Te animamos a que revises y soluciones estos problemas.

Los 2 principales problemas que se han detectado, ordenados por número de páginas afectadas:

El valor del atributo "width" de la etiqueta "amp-iframe" no es válido

El valor del atributo de la etiqueta AMP "frameborder" no es válido en la etiqueta "amp-iframe"

**Comment by danielperez9430** [comment]
Este el archivo de soundcloud que tengo insertado:

`<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/386022539&amp;color=ff5500"></iframe>`

Link que me da error: https://search.google.com/test/amp?url=https%3A%2F%2Ftecnonucleous.com%2F2018%2F02%2F13%2Fcuanto-cuestan-las-claves-rdp-de-windows%2F&skip_amp_follow=true

## Correo de Google

> Search Console ha detectado que hay 2 nuevos problemas de Accelerated Mobile Pages en tu sitio web. Por este motivo, es posible que la experiencia de Accelerated Mobile Pages se vea afectada en los resultados de la Búsqueda de Google. Te animamos a que revises y soluciones estos problemas.
> 
> Los 2 principales problemas que se han detectado, ordenados por número de páginas afectadas:
> 
> El valor del atributo "width" de la etiqueta "amp-iframe" no es válido
> 
> El valor del atributo de la etiqueta AMP "frameborder" no es válido en la etiqueta "amp-iframe"
