### ISSUE TITLE
Checkbox en el apartado de Subscribirse para cumplir la GDPR

### ISSUE THREAD

**Issue by danielperez9430** [godofredoninja/Mapache#69]
Según estuve leyendo hace falta añadir algo más al formulario para pedir el consentimiento y evitar problemas con la GDPR. Tú que opinas?

Info: https://blog.mailrelay.com/es/2017/12/04/formularios-nuevo-reglamento-de-proteccion-de-datos 
https://createria.es/ejemplo-de-formulario-adecuado-al-gdpr/

**Comment by cmilanf** [comment]
Desde mi punto de vista, esto recae en responsabilidad del motor de Ghost, dando el Theme soporte a ello. Actualmente la funcionalidad de suscriptores en Ghost es beta y está bien lejos de cumplir la GPDR: doble consentimiento, baja con sólo seguir un enlace en el email recibido, etc...

No me ha quedado más remedio que desactivarlo por ahora e informar a mis suscriptores.

**Comment by danielperez9430** [comment]
@cmilanf si lo del envío nativo aún no funciona. Pero es importante lo del checkbox, lo de las subscripciónes/bajas tienes que hacerlo de forma externa con servicio como mailchap y cada x tiempo limpias la lista que almacena Ghost, ya que los registros pasan a tu proveedor de emails.
