### ISSUE TITLE
Koenig editor support

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#71]
Koenig editor was introduced in the lab and needs theme adjustments: https://forum.ghost.org/t/koenig-editor-beta-release/1284

**Comment by PlanetVaster** [comment]
Ghost 2.0 is official now, when updating I get these errors:

> File: amp.hbs
    - The {{#author}} block helper should be replaced with {{#primary_author}}
    - The {{#if author.*}} block helper should be replaced with {{#if primary_author.*}}
        or {{#if authors.[#].*}}
    - Replace the {{author.bio}} helper with {{primary_author.bio}} or {{authors.[#].bio}}
    File: partials\article-author.hbs
    - The {{#author}} block helper should be replaced with {{#primary_author}}
    File: partials\article-byline.hbs
    - The {{#author}} block helper should be replaced with {{#primary_author}}
    File: partials\entry.hbs
    - The {{#author}} block helper should be replaced with {{#primary_author}}
    File: styles
    - The .kg-width-wide CSS class is required to use your theme with 2.0
    - The .kg-width-full CSS class is required to use your theme with 2.0

**Comment by danielperez9430** [comment]
Hi mate. Is a Know insure. The new version is coming, check the new design here: https://github.com/godofredoninja/Mapache/issues/76#issuecomment-414790494
