### ISSUE TITLE
homeTitleTyped and homeBtnTitle not working

### ISSUE THREAD

**Issue by k1ngf15h3r** [godofredoninja/Mapache#72]
Hi I just came over your great theme and started to configure some points.

When I configure homeTitleTyped or homeBtnTitle I can not see any changes. Also defining the css stylesheet in the blog header code-injection I see no changes.

Have you a suggestion what I am doing wrong?

**Comment by danielperez9430** [comment]
Add in Blog Footer in code injection
<script>
/* 03. Home BTN <SUBSCRIBE> */
var homeBtnTitle = 'Name';
var homeBtnURL = 'https://t.me/...';
</script>

**Comment by danielperez9430** [comment]
And download the laster version of ghost. I use this teme and 0 insures with this
