### ISSUE TITLE
Ghost 2.0 Now Official

### ISSUE THREAD

**Issue by danielperez9430** [godofredoninja/Mapache#76]
Today ghost present the estable release of Ghost 2.0 🤗🤗🤗

**Comment by godofredoninja** [comment]
Hi.

I'm working on a new version of Mapache.

— It's already at 80%. When I'm done creating the theme, I'll update it right away.

![screenshot_2018-08-21 zetaminds](https://user-images.githubusercontent.com/10253167/44423725-72632d80-a54c-11e8-83ed-2ac798745838.jpg)

**Comment by danielperez9430** [comment]
Una cosa podrías poner un Checkbox en la sección de subscribirse por email. Es por el tema de la GDPR. Y es necesario que tenga un botón de confirmación (sin estar previamente marcdado) para aceptar las condiciones de privacidad

**Comment by godofredoninja** [comment]
Acabo de subir la versión DEV de mapache. puedes descargar y probar en tu versión local de Ghost y luego me envías tus opiniones para poder mejorarlo. 

añade estas configuraciones en Ghost sección `code injection/blog footer`
```html
<script>
    /* 01. Social Media Follow*/
    var followSocialMedia = {
        'youtube': 'https://goo.gl/266Xvw',
        'instagram': 'https://www.instagram.com/godofredoninja/',
        'github': 'https://github.com/GodoFredoNinja',        
	};
    
    /* 03. Disqus Comment Settings */
	var disqusShortName = 'GodoFredoNinja';
    
    /* Facebook Comments => en_US - es_ES */
    var facebookLocaleCommentsDisable = 'en_US';
    
    /* Menu */
    var footerLinks = {
        'Terminos': 'https://goo.gl/266Xvw',
        'Sobre Mi': 'https://www.instagram.com/godofredoninja/',
        'Actualidad': 'https://github.com/GodoFredoNinja',  
    };
        
    /* instgram */
    var instagramToken = '1397790551.1aa422d.37dca7d33ba34544941e111aa03e85c7';
    var instagramUserId = '1397790551';
    var instagramUserName = 'GodoFredoNinja';
</script>
```

— La noche me tomare libre para poder trabajar y terminar de una vez. 

— En tu prueba intenta utilizar toda las plantillas que tiene Mapache para publicar Artículos. Si tu articulo es video añade la etiqueta `#video` si tu articulo es Imagen añade la etiqueta `#image`

**Comment by danielperez9430** [comment]
Perfecto a la noche lo pruebo. No sé si llegaste a ler lo de "Content Collections" en https://blog.ghost.org/2-0/ sería interesante una plantilla para los Podcast, yo tenía pensado en unos meses subir Podcast y esa función parece muy interesante.

Tú qué opinas sería posible? Por el momento ningún tema existente tiene esa opción

**Comment by danielperez9430** [comment]
Primer Bug: alto consumo de recursos en Firefox

![Captura](https://i.imgur.com/f7zdRLl.jpg)

**Comment by danielperez9430** [comment]
En la vista móvil faltan iconos:

![Faltan iconos](https://i.imgur.com/wTzlTrp.jpg)

![Faltan iconos](https://i.imgur.com/mllb6Qp.jpg)

Además de que surgen bloqueos por la alta carga que genera en el navegador

**Comment by danielperez9430** [comment]
El supuesto Script que causa el bloqueo:

![bloqueo](https://i.imgur.com/RCfCS2s.jpg)

**Comment by danielperez9430** [comment]
Video demostración de otros bugs como el de la flecha:

<iframe width="560" height="315" src="https://www.youtube.com/embed/2KbRw8eNe6I" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

Unas 3 personas estuvimos probandolo en varios navegadores y esto es todo lo que encontramos hasta el momento

**Comment by godofredoninja** [comment]
Hola.

Puede ser que tengas problemas con el CACHE.

Acabo de actualizar Mapache. espero que solucione eses errores mostrados.

si sigue teniendo los mismos errores hágame saber para buscar una mejor solución.

**Comment by danielperez9430** [comment]
Sigue pasando lo del bloqueo con Firefox principalmente tanto en Android como PC

**Comment by MaluNoPeleke** [comment]
@godofredoninja Could you please integrate the new gallery card from Ghost 2.1?
https://themes.ghost.org/docs/ghost-editor#section-gallery-card

**Comment by godofredoninja** [comment]
@MaluNoPeleke Already I add the `css` required.

**Comment by danielperez9430** [comment]
@godofredoninja Cuando puedas lee el correo que te mandé

Y sobre el tema al logo de Discord no le falta color de fondo?

![foto](https://i.imgur.com/FityNpY.jpg)

**Comment by godofredoninja** [comment]
@danielperez9430 

Genial en la noche revisare mi correo. para encontrar tu Email.

Para que pueda aparecer el icono de RSS

solo remplaza  `feed` por `rss`. se me olvido actualizar la documentación.

Tu pagina se ve muy bien.

Posteriormente añadiré secciones para añadir anuncios de forma fácil. 

pero el retardo que esta sufriendo tu pagina creo se de debe a serviceWorker

— Este error arroja en la consola. 

`Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The script resource is behind a redirect, which is disallowed.`

**Comment by danielperez9430** [comment]
@godofredoninja eso era porque en este tema no copié los archivos de la PWA y daba un 404. Pero aún así acabo de borrar el código de la PWA del panel de ghost.

Aún así se sigue bloqueado en Firefox tanto en Android como en Pc. Seguiré investigando pero es muy raro. Hasta quite todos los anuncios de Google y salía lo mismo.

**Comment by danielperez9430** [comment]
@godofredoninja Este es el reporte de Firefox sobre el error en cuestión que termina bloqueando el navegador. Por el momento solo pasa en Firefox limpié el Code injection y puse todo actualizado. Aún así sigue pasando lo mismo. Te adjunto todo el reporte


```
Script terminated by timeout at: 
F.SortedSet.prototype.add@https://tecnonucleous.com/assets/scripts/main.js?v=1753026bb1:62:198 F.Index.prototype.add/<@https://tecnonucleous.com/assets/scripts/main.js?v=1753026bb1:66:1610 F.Index.prototype.add@https://tecnonucleous.com/assets/scripts/main.js?v=1753026bb1:66:1464 loadAPI/</<@https://tecnonucleous.com/assets/scripts/main.js?v=1753026bb1:33:2090 loadAPI/<@https://tecnonucleous.com/assets/scripts/main.js?v=1753026bb1:33:1700 u@https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:27452 fireWith@https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:28202 k@https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:77649 n/<@https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:79907
```

Pues bueno, lo que he descubierto es que hay un buscador a nivel de frontend llamado ghostHunter

este para buscar usa el motor lunr, que tiene un Index

este llama a lunr sorted set

que tiene una funcion add


en esta posiblemente se queda pillada en el bucle de la fuincion: for (t = 0; t < arguments.length; t++) e = arguments[t],

**Comment by godofredoninja** [comment]
@danielperez9430  Hey hola.

Yo acabo de actualizar mi pagina y tengo el tema Mapache corriendo normal sin problemas.

http://godofredo.ninja/

**Comment by danielperez9430** [comment]
@godofredoninja Si acabamos de verlo y no me da problemas tú web. Yo creo que en la mía puede ser debido al gran volumen de post que tiene la web. Porque acabas usando la API de Ghost para bajarlos todos en la función del buscador. Esto crea un archivo muy pesado que relentiza el navegador y hace que llegue a bloquearse

**Comment by godofredoninja** [comment]
@danielperez9430  Tienes razón.

El buscador que utilizo es [ghostHunter](https://github.com/jamalneufeld/ghostHunter) y esto dispara de inmediato a la API de ghost. la idea seria retardar el llamado o decir que se ejecute cuando uno hace click en el buscador. ahora estoy intentando utilizar [Fuse](https://github.com/krisk/Fuse) para realizar búsquedas. 

— Pero creo que estés buscadores serán buenos para pequeñas paginas. 

— El equipo de Ghost recomienda [Agolia](https://forum.ghost.org/t/search-for-ghost/832/2)

**Comment by danielperez9430** [comment]
@godofredoninja more Agolia y es súper caro 😅. No sé si sería posible montar un buscador externo dentro del servidor que funcione como API. Algo tipo OpenSearch.

Me podrías decir como puedo desactivar el buscador de forma temporal en el tema.

Seguiré investigando para ver como se podría solucionar. Aproximadamente tendré unos 1500 post

**Comment by danielperez9430** [comment]
@godofredoninja Gracias, por lo menos ahora funciona bien la página, el único problema sigue siendo el buscador en cuanto toco en la lupa y escribo ya se colapsa el navegador. Quitando eso el resto funciona perfectamente.Podrias indicarme como quitar o desactivar la lupa. Estoy pensando o en meter un buscador tipo Google, DuckDuckGo o similar en vez de usar el nativo para evitar que al bajar ese Json tan grande bloque el navegador.

**Comment by godofredoninja** [comment]
@danielperez9430 Si deseas ocultar el icono del buscador entonces añade css en tu configuración de ghost en la sección código y `header code`

```html
<style>
.search-toggle, .header-line { display:none !important }
</style>
```

**Comment by danielperez9430** [comment]
@godofredoninja Gracias, es que también ghost hunter me sobrecargaba la web porque creaba un efecto de DDoS la información la puso un ceo de ghost https://github.com/jamalneufeld/ghostHunter/issues/66

Y mientras no saquen una mejora los de ghost tendré que prescindir temporalmente del buscador.

Y sobre la PWA (Progresive Web App) ya la tengo pública en la siguiente url: https://gitlab.com/Tecnonucleous/pwa  Aún falta el tema de las notificaciones y poco menos. Pero funciona sin problema

**Comment by danielperez9430** [comment]
@godofredoninja Me parece bien, ya lo había visto ayer en la actualización que mandan los de Ghost de su foro. Una cosa hay un problema con el tema del color y la inyección de código. Si quiere el tema por ejemplo en azul solo le cambia la parte principal de la web y no las vistas /amp , estaba mirando de cambiarlo manualmente pero hay que cambiar demasiados archivos.

Así es como lo tengo puesto:
```css
<!-- Estilos -->
<style>
:root {
  --primary-color: #0273d4;
  --header-color: #ddecfa;
  --header-color-hover: #FFFFFF;
  --post-color-link: #5ec1fe;
  --story-cover-category-color: rgb(201, 230, 255);
  --footer-color-link: rgba(164, 209, 248, 0.8);
  --composite-color: #FF5B5E;
}
.button--primary {
    border-color: #0273d4;
    color: #0273d4;
}
.u-accentColor--iconNormal {
    color: #0273d4;
    fill: #0273d4;
}
.button--dark:hover {
    background: #0273d4;
    border-color: #0273d4;
}
mark {background-image: linear-gradient(to bottom, #e1f5fe, #e1f5fe) !important;}
.search-toggle, .header-line { display:none !important }
</style>
```

**Comment by danielperez9430** [comment]
Y por otra parte estaba haciendo lo de corregir la "vulnerabilidad" de target="_blank

Más información: https://ayudawp.com/la-vulnerabilidad-target_blank-la-solucion-relnoopener-noreferrer-wordpress/

Links internos:
target="_blank" rel="noopener noreferrer"

Links externos:
target="_blank" rel="nofollow noopener noreferrer"

En cuanto acabe el edit mando un commit que lo estoy haciendo en un reporte privado en gitlab
