### ISSUE TITLE
Amp errors with Ghost version 2

### ISSUE THREAD

**Issue by danielperez9430** [godofredoninja/Mapache#77]
Mapache theme has 5 errors and 1 warning

? View error and warning details? Yes

Errors
    File: amp.hbs
    - The {{#author}} block helper should be replaced with {{#primary_author}}
    - The {{#if author.*}} block helper should be replaced with {{#if primary_author.*}}
        or {{#if authors.[#].*}}
    - Replace the {{author.bio}} helper with {{primary_author.bio}} or {{authors.[#].bio}}

    File: partials/article-author.hbs
    - The {{#author}} block helper should be replaced with {{#primary_author}}

    File: partials/article-byline.hbs
    - The {{#author}} block helper should be replaced with {{#primary_author}}

    File: partials/entry.hbs
    - The {{#author}} block helper should be replaced with {{#primary_author}}

    File: styles
    - The .kg-width-wide CSS class is required to use your theme with 2.0
    - The .kg-width-full CSS class is required to use your theme with 2.0

Warnings
    File: package.json
    - package.json property keywords should contain ghost-theme

**Comment by godofredoninja** [comment]
I just upgraded to a new Mapache version fixing all the bugs.
