### ISSUE TITLE
Nav broke in safari(latest), but working on Chorme(latest)

### ISSUE THREAD

**Issue by somenathghosh** [godofredoninja/Mapache#8]
Nav bar is completely out of position on Safari. Coming as list - Menu icon --> search bar --> fb icon

**Comment by somenathghosh** [comment]
Are you fixing it ? Waiting for the fix.

**Comment by somenathghosh** [comment]
do you have a fix for it ?

**Comment by godofredoninja** [comment]
Browsers are supported by Mapache
http://caniuse.com/#search=flex

Show me your page to give a solution.
