### ISSUE TITLE
Some issues with 3.0.2

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#80]
I am experiencing the following issues with 3.0.2:

1. The "Subscribe" button doesn't get translated (but a translation exists in the [de.json](https://github.com/godofredoninja/Mapache/issues/81))
2. I would like to make use of a gallery feature for articles with more than one image automatically. For that I am using featherlight with this code
```
    var img = jQuery('.post img');
    img.each(function() {
       var element = jQuery(this);
        var a = jQuery('<a />', {href: element.attr('src'), 'data-featherlight': 'image', 'class': 'gallery'});
        element.wrap(a);
    });    
    $('.gallery').featherlightGallery();
```
With Mapache 3.0.2 a second image viewer is active automatically. How to deactivate that (or enable automatic swiping to the next available image with it)?
3. At https://www.peleke.de/social/ and https://www.peleke.de/fotos/ there is an issue with underlined links that shouldn't be underlined and especially for the first link also some CSS issues.
4. You forgot to add Disqus comment count in the code injection readme:
```
<!-- Disqus Comments Count-->
<script id="dsq-count-scr" src="//peleke.disqus.com/count.js" async></script>
```
5. The font is loading a little bit slowly. Is there a possibility to improve that?

**Comment by godofredoninja** [comment]
fonts are loaded asynchronously, that's why it takes a few seconds.

For the following versions I will try to solve.

To zoom out of the images add this in your ghost settings in the footer code section.

```html
<script>
setTimeout(function(){
  $('.post-body').find('img').removeAttr('data-action');
}, 500);
</script>
```

**Comment by godofredoninja** [comment]
Hi Bro.

How are you?

— Add this piece of code to your article in the section Code Injection and then post header.

```html
<style>
.post-body a {
    box-shadow: none !important;
}
.post-body a:hover {
    box-shadow: none !important;
}
</style>
```

**Comment by MaluNoPeleke** [comment]
Thanks a lot!
