### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by kacperduras** [godofredoninja/Mapache#87]
How can I change font in easily way?

**Comment by godofredoninja** [comment]
Hi 😄 

- Roboto => Main typographic font and for the titles
- Merriweather => Typographic font for the content
- Roboto Mono => Typographic font for codes

— Here you can add the main font that will load faster

https://github.com/godofredoninja/Mapache/blob/5e619807f1473a67cc5e8bd69aab4b795dc0149a/default.hbs#L17

— In these lines it adds the secondary typographic fonts which will be loaded in an async way

https://github.com/godofredoninja/Mapache/blob/5e619807f1473a67cc5e8bd69aab4b795dc0149a/default.hbs#L64-L65

— When you're done making changes add the following code with the font name in your ghost settings in the code - blog header section

```html
<style>
/* Primary Font*/
body, h1, h2, h3, h4, h5, h6 {
  font-family: 'your_font';
}

/*2. font*/
.story-excerpt,
.post-excerpt,
.post-inner {
  font-family: 'your_font';
}
</style>
```

**Comment by kacperduras** [comment]
Thanks!
