### ISSUE TITLE
Broken images with 3.0.4

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#90]
[Version 3.0.4.](https://github.com/godofredoninja/Mapache/commit/c4fa41446cd0eed4558c54fe6b1f04cf8c75bf5e) breaks images if the server doesn't support (optional) sharp library which enables dynamic image sizes feature. 
Is there a way to toggle between both methods?

**Comment by godofredoninja** [comment]
Hello Bro @MaluNoPeleke 😄 

To be able to understand you, you tell me that you need sharper images. For the entries of the articles

**Comment by MaluNoPeleke** [comment]
It is not about sharper images but about images at all.
Take a look at this screenshot with 3.0.4 active:
![image](https://user-images.githubusercontent.com/1446541/51843184-ba178d80-2312-11e9-9abb-16b0538c551e.png)
I have a hoster with CentOS 6 which doesn't offer the installation of the sharp library which is [necessary for dynamic images](https://github.com/TryGhost/Ghost/pull/10184#pullrequestreview-184625891).
This theme doesn't seem to support Ghost without optional sharp library anymore with 3.0.4 that's why I have created this ticket.
Is is possible to add that compatibility again?
https://github.com/TryGhost/Ghost/issues/10421

**Comment by godofredoninja** [comment]
At the moment you would have to go back to a [previous version](https://github.com/godofredoninja/Mapache/tree/v3.0.3) of Mapache.

Until we wait for ghost people to solve that problem.

If this is not resolved in the short term I will create a Mapache branch where I will not use the dynamic images.

**Comment by godofredoninja** [comment]
HI @MaluNoPeleke 

This mistake has already been solved by the ghost people.

So this issue will be closed.
