### ISSUE TITLE
Comments box on mobile 

### ISSUE THREAD

**Issue by thatcriticguy** [godofredoninja/Mapache#91]
First, thanks for the theme, it's amazing. I have one small issue to report. When on mobile and reading a story, if you click on the comments box which normally slides open the comments on the side, it does so but prevents the user from scrolling up to see them. This has been testing on multiple devices using Chrome.

**Comment by godofredoninja** [comment]
Hi @thatcriticguy  😄 

Thank you for informing me of the possible errors you found.

I'm checking the scroll in the comments box and see that it's working normally.

![Mapache theme for Ghost Comments](https://user-images.githubusercontent.com/10253167/51724844-3cf7ca00-202d-11e9-9268-b51f8ceefb76.gif)


— But if in your case. There is still no scroll in the comments box. you can add some styles. please copy the code below and paste it into your ghost settings in the section. `Code injection > Blog Header`

```html
<style>@media only screen and (max-width: 766px){.post-comments{overflow-y:scroll}}</style>
```
---

👷 In the next few days I will be making updates to improve searches using ghost version 2 of Api. 

— If you have more suggestions for improving the Mapache theme for Ghost don't hesitate to tell me. Together we will build one of the best themes for ghost. 

😄
