### ISSUE TITLE
Error in search with custom links

### ISSUE THREAD

**Issue by danielperez9430** [godofredoninja/Mapache#93]
If your ghost posts urls are of this type:

`domain.com/year/mouth/day/slug..`

The results in search is:

`domain.com/slug`

The links that returns the search engine of ghost do not exist, the users always receive errors when open this urls

**Comment by godofredoninja** [comment]
Hello 😄 

Thank you for reporting this error.

Mapache is becoming an excellent theme for ghost. 

It's very easy to play with the ghost Api data for the Mapache search engine

To solve this problem is very easy, just do the following:

```html
<script>
    var searchSettings = {
        key: 'YOUR_API',
        host: 'https://demo.com',
        api: {
            parameters: {
                fields: ['title', 'url'],
            },
		},
        template: function (result) {
            return '<a href="' + result.url + '">' + result.title + '</a>';
        },
    };
</script>
```

**Comment by godofredoninja** [comment]
Hi @danielperez9430 

I want to ask you if the problem you had was solved.

Or you need help 🤔

**Comment by danielperez9430** [comment]
Fixed @godofredoninja Thanks you

**Comment by danielperez9430** [comment]
Fixed @godofredoninja Thanks you
