### ISSUE TITLE
How to hide toolbar when scrolling

### ISSUE THREAD

**Issue by leolorenzoluis** [godofredoninja/Mapache#94]
As title says, and also how do you show all the social icons like your website does?

**Comment by godofredoninja** [comment]
Hello @leolorenzoluis 

In my blog I am using [Simply theme for ghost](https://github.com/godofredoninja/simply)

And you can read the documentation on how to add your social media

**Comment by leolorenzoluis** [comment]
@godofredoninja I tried reading the docs, but and played around with it and I only set up a local variable for say Github, but then tried adding some more but it always hide some of the social bars unlike yours
