### ISSUE TITLE
Search does nothing

### ISSUE THREAD

**Issue by thecriticguy** [godofredoninja/Mapache#95]
I just updated to the latest version of the theme and search isn't functioning. If I click on search and start typing something, no results show. If I hit enter, I get redirected to the home page.

**Comment by danielperez9430** [comment]
Hi,
You need to go to Integrations > + Add custom integration and copy the API Key.

Before go to Settings -> Code Injection -> Blog Footer and change the host for your URL and key with your API Key

```
/* 06. Search Settings */
var searchSettings = {
  key: 'ADD_YOUR_API_KEY',
  host: 'https://demo.ghost.io',
  /* This is optional */
  options: {
    keys: [
      'title',
    ],
    limit: 10,
  },
  /* This is optional to perform filtering of the ghost api */
  api: {
    resource: 'posts',
    parameters: {
      limit: 'all',
      fields: ['title', 'slug'],
      filter: '',
      include: '',
      order: '',
      formats: '',
    },
  },
};

```

**Comment by thecriticguy** [comment]
It still isn't doing anything. I have done both of these things.

**Comment by danielperez9430** [comment]
check that in the host url do not put the "/" to the end of the domain url

Example:
`https://google.es` (correct)
`https://google.es/` (wrong)

if you still can not get it to work write the code you're use here

**Comment by thatcriticguy** [comment]
Got it thanks, fixed.

**Comment by godofredoninja** [comment]
@danielperez9430 Thanks for taking the time and answering

As this issue is already resolved, it has to be closed
