### ISSUE TITLE
Cover image not showing

### ISSUE THREAD

**Issue by EthanZeigler** [godofredoninja/Mapache#99]
Cover images don't load, even when rendered correctly by other themes. Just a black box shows up. Pretty straightforward.

See blog.ethanzeigler.com for an example.

**Comment by godofredoninja** [comment]
Hello @EthanZeigler 

I just checked and everything's fine.

Make sure the image is added to your ghost settings.

**Comment by EthanZeigler** [comment]
That's the thing. I did several times. Only mapache has this issue.

Caffeine (unconfigured)
<img width="1280" alt="Screen Shot 2019-04-02 at 11 15 40 PM" src="https://user-images.githubusercontent.com/9123320/55450513-60933f80-559d-11e9-85bf-d7896abab622.png">

Casper
<img width="1280" alt="Screen Shot 2019-04-02 at 11 15 14 PM" src="https://user-images.githubusercontent.com/9123320/55450531-76a10000-559d-11e9-895d-03da1db4da06.png">

Mapache
<img width="1280" alt="Screen Shot 2019-04-02 at 11 16 02 PM" src="https://user-images.githubusercontent.com/9123320/55450539-7e60a480-559d-11e9-84b7-d3bb9569ec31.png">

**Comment by godofredoninja** [comment]
The problem is because you're using an old version of ghost.

**Comment by EthanZeigler** [comment]
What the heck? I could have sworn that was the first thing I checked.

It works now. Thank you!
